- name: inherit-tasks
  hosts: localhost
  vars:
  - jaya: dongi
    pani: cutie
  tasks:
  - name: print the values from play
    ansible.builtin.debug:
      msg: "you know jaya is {{jaya}} and pani is always {{pani}}"
  - name: print the values from play
    vars:
      - jaya: bad
        pani: cutie
        suzu: good
    ansible.builtin.debug:
      msg: "you know jaya is {{jaya}} and pani is always {{pani}} suzu is {{suzu}}"



