- name: create user
  hosts: localhost
  tasks:
  - name: check user exits or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print the exit status
    ansible.builtin.debug:
      msg: "{{out.rc}}"

  - when: out.rc != 0
    name: create user
    ansible.builtin.user:
    user: roboshop


