- name: create user
  hosts: localhost
  tasks:
  - name: check user exits or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print the exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"


  - name: create user roboshop
    became: yes
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0





