- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - {name: 'nginx', state:'absent' }
    - {name: 'postfix', state: 'installed'}